plugins {
    id 'application'
    id 'java'
}

group = 'dev.abhay7'
version = '1.0'

application {
    mainClass = 'dev.abhay7.skribbl.client.Main'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.formdev:flatlaf:3.2'
    implementation 'org.json:json:20240303'
    implementation 'org.bouncycastle:bcprov-jdk18on:1.80'
    implementation project(':server')
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    manifest {
        attributes(
            'Main-Class': application.mainClass
        )
    }
}