plugins {
    id 'java'
    id 'application'
}

group = 'dev.abhay7'
version = '1.0'

application {
    mainClass = 'dev.abhay7.skribbl.server.Main'
}

java {
    sourceCompatibility = JavaVersion.VERSION_24
    targetCompatibility = JavaVersion.VERSION_24
}

jar {
    manifest {
        attributes(
            'Main-Class': application.mainClass
        )
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'org.json:json:20240303'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed", "standardOut", "standardError"
        showStandardStreams = true
    }
}
