plugins {
    id 'java'
    id 'application'
}

group = 'dev.abhay7'
version = '1.0'

application {
    mainClass = 'dev.abhay7.skribbl.server.Main'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    manifest {
        attributes(
            'Main-Class': application.mainClass
        )
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.junit.jupiter:junit-jupiter:5.10.0' // Or latest version
}

test {
    useJUnitPlatform()
}
